name: Gendiff Actions
run-name: ${{ github.actor }} Gendiff Actions in progress ğŸš€
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Test code
        uses: actions/checkout@v4
      - run: make test
      - run: npm install -g yarn
      - run: yarn install
      - run: yarn build
      - run: yarn test
        name: coverage
        runs-on: ubuntu-latest
        steps:
        - shell: bash
        - uses: actions/checkout@main
        - uses: actions/setup-node@main
          with:
            node-version: '12'
        - run: npm install -g yarn
        - run: yarn install
        - run: yarn build
        - uses: paambaati/codeclimate-action@v2.2.4
          env:
            CC_TEST_REPORTER_ID: ${{ secrets.codeclimatCoverage }}
          with:
            coverageCommand: yarn coverage
      - name: Check linting
        run: make lint
      - run: echo "ğŸ This job's status is ${{ job.status }}."
